### ISSUE TITLE
Question: Why not Clojure?

### ISSUE THREAD

**Issue by stathissideris** [bhauman/cljs-test-display#2]
Just discovered this and from the screenshots it looks awesome, many thanks for your work here and elsewhere! Would it be possible/desirable to extend this to include Clojure tests as well? It looks like a very friendly way to display test outcomes.

**Comment by bhauman** [comment]
Clojure would probably require an entirely different implementation. And you'd have to think about what you are wanting, are you wanting live updates as you code? Or are you just wanting a single display after running the tests just once?  In the first case you would need to supply a server capable of push or long polling and you'd have to serialize and display data. This is a significant increase to the complexity of the current codebase so it would probably need to be a different library.  In the second case you would just output some html and pop open a browser to view the results.

**Comment by stathissideris** [comment]
Thanks for explaining. Live updates would be great, especially now that there are rumours about a test runner coming out of the Hickey/Miller team. I think a separate library would make sense, but if it could be somehow integrated to this display that would be ideal, because it would allow developers to view all the test results "under one roof" in a consistent way. I'll see if I can find some time to look into it, thanks!
